# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mgtools
                                 A QGIS plugin
 Conjunto de Herramientas para el Procesado de Información Geoestadisitica 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-11
        copyright            : (C) 2021 by Francisco Contreras, GeoSIG
        email                : Francisco Contreras93@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mgtools class from file mgtools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mgtools import mgtools
    return mgtools(iface)
